<?php

declare(strict_types=1);

use Symfony\Component\Config\Definition\Configurator\DefinitionConfigurator;

return static function (DefinitionConfigurator $definition): void {
    $definition->rootNode()
        ->children()
            ->stringNode('url')
                ->info('Absolute or relative document URL fetched by the browser.')
                ->defaultNull()
            ->end()
            ->stringNode('content')
                ->info('Raw JSON or YAML embedded in the page. Overrides url.')
                ->defaultNull()
            ->end()
            ->stringNode('file')
                ->info('Local file embedded in the page. Use %kernel.project_dir% for project-relative paths. Overrides content and url.')
                ->defaultNull()
            ->end()
            ->arrayNode('sources')
                ->info('Multiple documents. Overrides single-document settings.')
                ->performNoDeepMerging()
                ->validate()
                    ->ifTrue(static fn (array $sources): bool => !array_is_list($sources))
                    ->thenInvalid('The sources option must be a list of documents.')
                ->end()
                ->arrayPrototype()
                    ->children()
                        ->stringNode('title')->defaultNull()->end()
                        ->stringNode('slug')->defaultNull()->end()
                        ->stringNode('url')->defaultNull()->end()
                        ->stringNode('content')->defaultNull()->end()
                        ->stringNode('file')->defaultNull()->end()
                        ->booleanNode('default')->defaultFalse()->end()
                    ->end()
                ->end()
            ->end()
            ->stringNode('cdn')
                ->info('URL of the Scalar API Reference standalone bundle.')
                ->defaultValue('https://cdn.jsdelivr.net/npm/@scalar/api-reference@1.69.0/dist/browser/standalone.js')
                ->cannotBeEmpty()
            ->end()
            ->stringNode('path')
                ->info('Path of the API reference route.')
                ->defaultValue('/scalar')
                ->cannotBeEmpty()
                ->validate()
                    ->ifTrue(static fn (string $v): bool => !str_starts_with($v, '/'))
                    ->thenInvalid('The path must start with a slash ("/"), got "%s".')
                ->end()
            ->end()
            ->arrayNode('configuration')
                ->info('Scalar options passed as JSON. Document inputs belong at the top level.')
                ->normalizeKeys(false)
                ->defaultValue([])
                ->variablePrototype()->end()
            ->end()
            ->arrayNode('scalar_options')
                ->info('Deprecated alias for configuration. Legacy values win when both maps set the same option.')
                ->normalizeKeys(false)
                ->defaultValue([])
                ->variablePrototype()->end()
            ->end()
            ->arrayNode('access_control')
                ->info('Access control for the API reference route.')
                ->addDefaultsIfNotSet()
                ->children()
                    ->enumNode('mode')
                        ->info('"public" — everyone may view the docs; "attribute" — require a security attribute.')
                        ->values(['public', 'attribute'])
                        ->defaultValue('public')
                    ->end()
                    ->stringNode('attribute')
                        ->info('Security attribute to check when mode is "attribute" (e.g. ROLE_ADMIN).')
                        ->defaultNull()
                        ->cannotBeEmpty()
                    ->end()
                ->end()
                ->validate()
                    ->ifTrue(static fn (array $v): bool => 'attribute' === $v['mode'] && null === $v['attribute'])
                    ->thenInvalid('An attribute is required when access_control.mode is "attribute".')
                ->end()
            ->end()
        ->end();
};
